name: Dev container prebuild

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  # pull_request:
  #   branches: ["main"]

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-tags: true

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: latest

      - name: Pre-build dev container image
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          imageName: registry.int.xeserv.us/devcontainer/yoke-stuff
          cacheFrom: registry.int.xeserv.us/devcontainer/yoke-stuff
          push: always
