apiVersion: x.within.website/v1
kind: App
metadata:
  name: uncle-ted
  labels:
    test-app: please-ignore
  annotations:
    overrides.yoke.cd/flight: https://minio.xeserv.us/mi-static/yoke/x-app/v1.wasm.gz
spec:
  image: ghcr.io/xe/x/uncle-ted
  replicas: 1
  autoUpdate: true

  healthcheck:
    enabled: false
    port: 3000
    path: /

  ingress:
    enabled: true
    host: uncle-ted.within.website
    clusterIssuer: letsencrypt-prod
    className: nginx